# Generated by Django 5.2 on 2025-04-12 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='isStaff',
            new_name='is_staff',
        ),
    ]
